// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city_score.proto

package com.nils.gprc.cityscore;

public interface CityScoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cityscore.CityScoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 city_score = 1;</code>
   * @return The cityScore.
   */
  int getCityScore();
}
