FROM amazoncorretto:17

COPY target/spring-demo-data-pipeline-0.0.1-SNAPSHOT.jar spring-demo-data-pipeline-0.0.1-SNAPSHOT.jar

EXPOSE 9010

ENTRYPOINT ["java","-jar","/spring-demo-data-pipeline-0.0.1-SNAPSHOT.jar"]