// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

/**
 * Protobuf type {@code scoresegment.ScoreSegmentExceptionResponse}
 */
public final class ScoreSegmentExceptionResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:scoresegment.ScoreSegmentExceptionResponse)
        ScoreSegmentExceptionResponseOrBuilder {
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    public static final int ERROR_CODE_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:scoresegment.ScoreSegmentExceptionResponse)
    private static final com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ScoreSegmentExceptionResponse>
            PARSER = new com.google.protobuf.AbstractParser<ScoreSegmentExceptionResponse>() {
        @java.lang.Override
        public ScoreSegmentExceptionResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        DEFAULT_INSTANCE = new com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse();
    }

    private int bitField0_;
    private com.google.protobuf.Timestamp timestamp_;
    private int errorCode_ = 0;
    private byte memoizedIsInitialized = -1;

    // Use ScoreSegmentExceptionResponse.newBuilder() to construct.
    private ScoreSegmentExceptionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ScoreSegmentExceptionResponse() {
        errorCode_ = 0;
    }

    public static com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor;
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ScoreSegmentExceptionResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new ScoreSegmentExceptionResponse();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.class, com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.Builder.class);
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     *
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    /**
     * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
     *
     * @return The enum numeric value on the wire for errorCode.
     */
    @java.lang.Override
    public int getErrorCodeValue() {
        return errorCode_;
    }

    /**
     * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
     *
     * @return The errorCode.
     */
    @java.lang.Override
    public com.nils.gprc.scoresegment.ScoreSegmentErrorCode getErrorCode() {
        com.nils.gprc.scoresegment.ScoreSegmentErrorCode result = com.nils.gprc.scoresegment.ScoreSegmentErrorCode.forNumber(errorCode_);
        return result == null ? com.nils.gprc.scoresegment.ScoreSegmentErrorCode.UNRECOGNIZED : result;
    }

    @java.lang.Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getTimestamp());
        }
        if (errorCode_ != com.nils.gprc.scoresegment.ScoreSegmentErrorCode.INVALID_ID_NUMBER_VALUE.getNumber()) {
            output.writeEnum(2, errorCode_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getTimestamp());
        }
        if (errorCode_ != com.nils.gprc.scoresegment.ScoreSegmentErrorCode.INVALID_ID_NUMBER_VALUE.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(2, errorCode_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof ScoreSegmentExceptionResponse other)) {
            return super.equals(obj);
        }

        if (hasTimestamp() != other.hasTimestamp()) return false;
        if (hasTimestamp()) {
            if (!getTimestamp()
                    .equals(other.getTimestamp())) return false;
        }
        if (errorCode_ != other.errorCode_) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTimestamp()) {
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + getTimestamp().hashCode();
        }
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + errorCode_;
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreSegmentExceptionResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code scoresegment.ScoreSegmentExceptionResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:scoresegment.ScoreSegmentExceptionResponse)
            com.nils.gprc.scoresegment.ScoreSegmentExceptionResponseOrBuilder {
        private int bitField0_;
        private com.google.protobuf.Timestamp timestamp_;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
        private int errorCode_ = 0;

        // Construct using com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.class, com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getTimestampFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            timestamp_ = null;
            if (timestampBuilder_ != null) {
                timestampBuilder_.dispose();
                timestampBuilder_ = null;
            }
            errorCode_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor;
        }

        @java.lang.Override
        public com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse getDefaultInstanceForType() {
            return com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse build() {
            com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse buildPartial() {
            com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse result = new com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.timestamp_ = timestampBuilder_ == null
                        ? timestamp_
                        : timestampBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.errorCode_ = errorCode_;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse) {
                return mergeFrom((com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse other) {
            if (other == com.nils.gprc.scoresegment.ScoreSegmentExceptionResponse.getDefaultInstance()) return this;
            if (other.hasTimestamp()) {
                mergeTimestamp(other.getTimestamp());
            }
            if (other.errorCode_ != 0) {
                setErrorCodeValue(other.getErrorCodeValue());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(
                                    getTimestampFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 16: {
                            errorCode_ = input.readEnum();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         *
         * @return Whether the timestamp field is set.
         */
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         *
         * @return The timestamp.
         */
        public com.google.protobuf.Timestamp getTimestamp() {
            if (timestampBuilder_ == null) {
                return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
            } else {
                return timestampBuilder_.getMessage();
            }
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder setTimestamp(com.google.protobuf.Timestamp value) {
            if (timestampBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                timestamp_ = value;
            } else {
                timestampBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder setTimestamp(
                com.google.protobuf.Timestamp.Builder builderForValue) {
            if (timestampBuilder_ == null) {
                timestamp_ = builderForValue.build();
            } else {
                timestampBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
            if (timestampBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) &&
                        timestamp_ != null &&
                        timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
                    getTimestampBuilder().mergeFrom(value);
                } else {
                    timestamp_ = value;
                }
            } else {
                timestampBuilder_.mergeFrom(value);
            }
            if (timestamp_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
            bitField0_ = (bitField0_ & ~0x00000001);
            timestamp_ = null;
            if (timestampBuilder_ != null) {
                timestampBuilder_.dispose();
                timestampBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getTimestampFieldBuilder().getBuilder();
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
            if (timestampBuilder_ != null) {
                return timestampBuilder_.getMessageOrBuilder();
            } else {
                return timestamp_ == null ?
                        com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
            }
        }

        /**
         * <code>.google.protobuf.Timestamp timestamp = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getTimestampFieldBuilder() {
            if (timestampBuilder_ == null) {
                timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                        getTimestamp(),
                        getParentForChildren(),
                        isClean());
                timestamp_ = null;
            }
            return timestampBuilder_;
        }

        /**
         * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
         *
         * @return The enum numeric value on the wire for errorCode.
         */
        @java.lang.Override
        public int getErrorCodeValue() {
            return errorCode_;
        }

        /**
         * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
         *
         * @param value The enum numeric value on the wire for errorCode to set.
         * @return This builder for chaining.
         */
        public Builder setErrorCodeValue(int value) {
            errorCode_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
         *
         * @return The errorCode.
         */
        @java.lang.Override
        public com.nils.gprc.scoresegment.ScoreSegmentErrorCode getErrorCode() {
            com.nils.gprc.scoresegment.ScoreSegmentErrorCode result = com.nils.gprc.scoresegment.ScoreSegmentErrorCode.forNumber(errorCode_);
            return result == null ? com.nils.gprc.scoresegment.ScoreSegmentErrorCode.UNRECOGNIZED : result;
        }

        /**
         * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
         *
         * @param value The errorCode to set.
         * @return This builder for chaining.
         */
        public Builder setErrorCode(com.nils.gprc.scoresegment.ScoreSegmentErrorCode value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            errorCode_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorCode() {
            bitField0_ = (bitField0_ & ~0x00000002);
            errorCode_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:scoresegment.ScoreSegmentExceptionResponse)
    }

}

