// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

public final class ScoreSegment {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_scoresegment_ScoreSegmentRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_scoresegment_ScoreSegmentResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\023score_segment.proto\022\014scoresegment\032\037goo" +
                        "gle/protobuf/timestamp.proto\"(\n\023ScoreSeg" +
                        "mentRequest\022\021\n\tid_number\030\001 \001(\004\"-\n\024ScoreS" +
                        "egmentResponse\022\025\n\rscore_segment\030\001 \001(\004\"\207\001" +
                        "\n\035ScoreSegmentExceptionResponse\022-\n\ttimes" +
                        "tamp\030\001 \001(\0132\032.google.protobuf.Timestamp\0227" +
                        "\n\nerror_code\030\002 \001(\0162#.scoresegment.ScoreS" +
                        "egmentErrorCode*R\n\025ScoreSegmentErrorCode" +
                        "\022\033\n\027INVALID_ID_NUMBER_VALUE\020\000\022\034\n\030ID_NUMB" +
                        "ER_CANNOT_BE_NULL\020\0012w\n\023ScoreSegmentServi" +
                        "ce\022`\n\025calculateScoreSegment\022!.scoresegme" +
                        "nt.ScoreSegmentRequest\032\".scoresegment.Sc" +
                        "oreSegmentResponse\"\000B\036\n\032com.nils.gprc.sc" +
                        "oresegmentP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_scoresegment_ScoreSegmentRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scoresegment_ScoreSegmentRequest_descriptor,
                new java.lang.String[]{"IdNumber",});
        internal_static_scoresegment_ScoreSegmentResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scoresegment_ScoreSegmentResponse_descriptor,
                new java.lang.String[]{"ScoreSegment",});
        internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor,
                new java.lang.String[]{"Timestamp", "ErrorCode",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }
    private ScoreSegment() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
