// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

public interface ScoreSegmentExceptionResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scoresegment.ScoreSegmentExceptionResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     *
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     *
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
     *
     * @return The enum numeric value on the wire for errorCode.
     */
    int getErrorCodeValue();

    /**
     * <code>.scoresegment.ScoreSegmentErrorCode error_code = 2;</code>
     *
     * @return The errorCode.
     */
    com.nils.gprc.scoresegment.ScoreSegmentErrorCode getErrorCode();
}
