// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

public interface ScoreSegmentRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:scoresegment.ScoreSegmentRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id_number = 1;</code>
     *
     * @return The idNumber.
     */
    long getIdNumber();
}
