// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city_score.proto

package com.nils.gprc.cityscore;

/**
 * Protobuf type {@code cityscore.CityScoreRequest}
 */
public final class CityScoreRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cityscore.CityScoreRequest)
        CityScoreRequestOrBuilder {
    public static final int CITY_CODE_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:cityscore.CityScoreRequest)
    private static final com.nils.gprc.cityscore.CityScoreRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<CityScoreRequest>
            PARSER = new com.google.protobuf.AbstractParser<CityScoreRequest>() {
        @java.lang.Override
        public CityScoreRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        DEFAULT_INSTANCE = new com.nils.gprc.cityscore.CityScoreRequest();
    }

    private int cityCode_ = 0;
    private byte memoizedIsInitialized = -1;
    // Use CityScoreRequest.newBuilder() to construct.
    private CityScoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private CityScoreRequest() {
    }

    public static com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.nils.gprc.cityscore.CityScore.internal_static_cityscore_CityScoreRequest_descriptor;
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.nils.gprc.cityscore.CityScoreRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.nils.gprc.cityscore.CityScoreRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<CityScoreRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new CityScoreRequest();
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.nils.gprc.cityscore.CityScore.internal_static_cityscore_CityScoreRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.nils.gprc.cityscore.CityScoreRequest.class, com.nils.gprc.cityscore.CityScoreRequest.Builder.class);
    }

    /**
     * <code>int32 city_code = 1;</code>
     *
     * @return The cityCode.
     */
    @java.lang.Override
    public int getCityCode() {
        return cityCode_;
    }

    @java.lang.Override
    public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (cityCode_ != 0) {
            output.writeInt32(1, cityCode_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (cityCode_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, cityCode_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof CityScoreRequest other)) {
            return super.equals(obj);
        }

        if (getCityCode()
                != other.getCityCode()) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CITY_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCityCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CityScoreRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.nils.gprc.cityscore.CityScoreRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code cityscore.CityScoreRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cityscore.CityScoreRequest)
            com.nils.gprc.cityscore.CityScoreRequestOrBuilder {
        private int bitField0_;
        private int cityCode_;

        // Construct using com.nils.gprc.cityscore.CityScoreRequest.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.nils.gprc.cityscore.CityScore.internal_static_cityscore_CityScoreRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.nils.gprc.cityscore.CityScore.internal_static_cityscore_CityScoreRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.nils.gprc.cityscore.CityScoreRequest.class, com.nils.gprc.cityscore.CityScoreRequest.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            cityCode_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.nils.gprc.cityscore.CityScore.internal_static_cityscore_CityScoreRequest_descriptor;
        }

        @java.lang.Override
        public com.nils.gprc.cityscore.CityScoreRequest getDefaultInstanceForType() {
            return com.nils.gprc.cityscore.CityScoreRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.nils.gprc.cityscore.CityScoreRequest build() {
            com.nils.gprc.cityscore.CityScoreRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.nils.gprc.cityscore.CityScoreRequest buildPartial() {
            com.nils.gprc.cityscore.CityScoreRequest result = new com.nils.gprc.cityscore.CityScoreRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.nils.gprc.cityscore.CityScoreRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.cityCode_ = cityCode_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.nils.gprc.cityscore.CityScoreRequest) {
                return mergeFrom((com.nils.gprc.cityscore.CityScoreRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.nils.gprc.cityscore.CityScoreRequest other) {
            if (other == com.nils.gprc.cityscore.CityScoreRequest.getDefaultInstance()) return this;
            if (other.getCityCode() != 0) {
                setCityCode(other.getCityCode());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            cityCode_ = input.readInt32();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>int32 city_code = 1;</code>
         *
         * @return The cityCode.
         */
        @java.lang.Override
        public int getCityCode() {
            return cityCode_;
        }

        /**
         * <code>int32 city_code = 1;</code>
         *
         * @param value The cityCode to set.
         * @return This builder for chaining.
         */
        public Builder setCityCode(int value) {

            cityCode_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int32 city_code = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCityCode() {
            bitField0_ = (bitField0_ & ~0x00000001);
            cityCode_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cityscore.CityScoreRequest)
    }

}

