// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city_score.proto

package com.nils.gprc.cityscore;

public interface CityScoreRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cityscore.CityScoreRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 city_code = 1;</code>
     *
     * @return The cityCode.
     */
    int getCityCode();
}
