// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city_score.proto

package com.nils.gprc.cityscore;

public final class CityScore {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cityscore_CityScoreRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cityscore_CityScoreRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cityscore_CityScoreResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cityscore_CityScoreResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cityscore_CityScoreExceptionResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cityscore_CityScoreExceptionResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020city_score.proto\022\tcityscore\032\037google/pr" +
                        "otobuf/timestamp.proto\"%\n\020CityScoreReque" +
                        "st\022\021\n\tcity_code\030\001 \001(\005\"'\n\021CityScoreRespon" +
                        "se\022\022\n\ncity_score\030\001 \001(\005\"~\n\032CityScoreExcep" +
                        "tionResponse\022-\n\ttimestamp\030\001 \001(\0132\032.google" +
                        ".protobuf.Timestamp\0221\n\nerror_code\030\002 \001(\0162" +
                        "\035.cityscore.CityScoreErrorCode*O\n\022CitySc" +
                        "oreErrorCode\022\033\n\027INVALID_CITY_CODE_VALUE\020" +
                        "\000\022\034\n\030CITY_CODE_CANNOT_BE_NULL\020\0012e\n\020CityS" +
                        "coreService\022Q\n\022calculateCityScore\022\033.city" +
                        "score.CityScoreRequest\032\034.cityscore.CityS" +
                        "coreResponse\"\000B\033\n\027com.nils.gprc.cityscor" +
                        "eP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_cityscore_CityScoreRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cityscore_CityScoreRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cityscore_CityScoreRequest_descriptor,
                new java.lang.String[]{"CityCode",});
        internal_static_cityscore_CityScoreResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_cityscore_CityScoreResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cityscore_CityScoreResponse_descriptor,
                new java.lang.String[]{"CityScore",});
        internal_static_cityscore_CityScoreExceptionResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_cityscore_CityScoreExceptionResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cityscore_CityScoreExceptionResponse_descriptor,
                new java.lang.String[]{"Timestamp", "ErrorCode",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }
    private CityScore() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
