// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

public interface ScoreSegmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scoresegment.ScoreSegmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 score_segment = 1;</code>
   * @return The scoreSegment.
   */
  long getScoreSegment();
}
