// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_segment.proto

package com.nils.gprc.scoresegment;

/**
 * Protobuf type {@code scoresegment.ScoreSegmentResponse}
 */
public final class ScoreSegmentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scoresegment.ScoreSegmentResponse)
    ScoreSegmentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScoreSegmentResponse.newBuilder() to construct.
  private ScoreSegmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScoreSegmentResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScoreSegmentResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nils.gprc.scoresegment.ScoreSegmentResponse.class, com.nils.gprc.scoresegment.ScoreSegmentResponse.Builder.class);
  }

  public static final int SCORE_SEGMENT_FIELD_NUMBER = 1;
  private long scoreSegment_ = 0L;
  /**
   * <code>uint64 score_segment = 1;</code>
   * @return The scoreSegment.
   */
  @java.lang.Override
  public long getScoreSegment() {
    return scoreSegment_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scoreSegment_ != 0L) {
      output.writeUInt64(1, scoreSegment_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scoreSegment_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, scoreSegment_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nils.gprc.scoresegment.ScoreSegmentResponse)) {
      return super.equals(obj);
    }
    com.nils.gprc.scoresegment.ScoreSegmentResponse other = (com.nils.gprc.scoresegment.ScoreSegmentResponse) obj;

    if (getScoreSegment()
        != other.getScoreSegment()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCORE_SEGMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScoreSegment());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.gprc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nils.gprc.scoresegment.ScoreSegmentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scoresegment.ScoreSegmentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scoresegment.ScoreSegmentResponse)
      com.nils.gprc.scoresegment.ScoreSegmentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nils.gprc.scoresegment.ScoreSegmentResponse.class, com.nils.gprc.scoresegment.ScoreSegmentResponse.Builder.class);
    }

    // Construct using com.nils.gprc.scoresegment.ScoreSegmentResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scoreSegment_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nils.gprc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
    }

    @java.lang.Override
    public com.nils.gprc.scoresegment.ScoreSegmentResponse getDefaultInstanceForType() {
      return com.nils.gprc.scoresegment.ScoreSegmentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nils.gprc.scoresegment.ScoreSegmentResponse build() {
      com.nils.gprc.scoresegment.ScoreSegmentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nils.gprc.scoresegment.ScoreSegmentResponse buildPartial() {
      com.nils.gprc.scoresegment.ScoreSegmentResponse result = new com.nils.gprc.scoresegment.ScoreSegmentResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nils.gprc.scoresegment.ScoreSegmentResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scoreSegment_ = scoreSegment_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nils.gprc.scoresegment.ScoreSegmentResponse) {
        return mergeFrom((com.nils.gprc.scoresegment.ScoreSegmentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nils.gprc.scoresegment.ScoreSegmentResponse other) {
      if (other == com.nils.gprc.scoresegment.ScoreSegmentResponse.getDefaultInstance()) return this;
      if (other.getScoreSegment() != 0L) {
        setScoreSegment(other.getScoreSegment());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              scoreSegment_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long scoreSegment_ ;
    /**
     * <code>uint64 score_segment = 1;</code>
     * @return The scoreSegment.
     */
    @java.lang.Override
    public long getScoreSegment() {
      return scoreSegment_;
    }
    /**
     * <code>uint64 score_segment = 1;</code>
     * @param value The scoreSegment to set.
     * @return This builder for chaining.
     */
    public Builder setScoreSegment(long value) {

      scoreSegment_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 score_segment = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScoreSegment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      scoreSegment_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scoresegment.ScoreSegmentResponse)
  }

  // @@protoc_insertion_point(class_scope:scoresegment.ScoreSegmentResponse)
  private static final com.nils.gprc.scoresegment.ScoreSegmentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nils.gprc.scoresegment.ScoreSegmentResponse();
  }

  public static com.nils.gprc.scoresegment.ScoreSegmentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScoreSegmentResponse>
      PARSER = new com.google.protobuf.AbstractParser<ScoreSegmentResponse>() {
    @java.lang.Override
    public ScoreSegmentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScoreSegmentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScoreSegmentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nils.gprc.scoresegment.ScoreSegmentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

